name: '1.0$(Rev:.r)'
trigger:
- master

parameters:
- name: updateInfrastructure
  type: boolean
  default: false
  displayName: Update Infrastructure
  values:
    - true
    - false

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'niobium-store'
  resourceGroupName: 'niobium-store'
  appName: 'niobiumstoreFunc'
  enableStagingSlot: true

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'Niobium/niobium'
      projectToPublish: '**/Niobium.Store.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      enabled: ${{ parameters.updateInfrastructure }}
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appName: $(appName)
      enableKeyVault: true
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      allowedOrigins: 'https://www.niobium.co.nz'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: 'niobiumstoredb'
        contributorPrincipalId: $(functionAppPrincipalId)
        allowedOrigins: 'http://localhost:7109,https://www.niobium.co.nz'

  - job: Messaging
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: 'niobiumstoresb'
        serviceBusQueueNames: ['ordercreated']
        dataOwnerPrincipalId: $(functionAppPrincipalId)

  - job: Subscription
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: 'niobiumemailsb'
        dataOwnerPrincipalId: $(functionAppPrincipalId)

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
      - Messaging
      - Subscription
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
      serviceBusFQDN: $[dependencies.Messaging.outputs['newServiceBusProperties.fullyQualifiedNamespace']]
      subscriptionServiceBusFQDN: $[dependencies.Subscription.outputs['serviceBusPermissionProperties.fullyQualifiedNamespace']]
    steps:
    - checkout: none
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]production"
      displayName: "Deploy to Production"
      condition: eq('${{ variables.enableStagingSlot }}', false)
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]staging"
      displayName: "Deploy to Staging"
      condition: eq('${{ variables.enableStagingSlot }}', true)
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": false
            },
            {
              "name": "ServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDN)",
              "slotSetting": false
            },
            {
              "name": "SubscriptionServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(subscriptionServiceBusFQDN)",
              "slotSetting": false
            },
            {
              "name": "PaymentServiceOptions:SecretAPIKey",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/STRIPE-SECRET/)",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretHashKey",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/HASH-SECRET/)",
              "slotSetting": true
            },
            {
              "name": "CaptchaOptions:Secrets:www.niobium.co.nz",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RECAPTCHA-SECRET-WWW-NIOBIUM-CO-NZ/)",
              "slotSetting": true
            },
            {
              "name": "CaptchaOptions:Secrets:www.zaps.co.nz",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RECAPTCHA-SECRET-WWW-ZAPS-CO-NZ/)",
              "slotSetting": true
            }
          ]
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        slotName: $(slotName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "PaymentServiceOptions:SecretAPIKey",
              "value": "sk_test_51RSwkoRt21XMpal8PaJpf5l6bGSGtgU1bueDBUL5mJw16bv5jPegj99Yw5yAXRSqaL0n0lFoan6JA6FOUdZWKKbb00a4PHlbrS",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretHashKey",
              "value": "012345678901234567890123456789AB",
              "slotSetting": true
            },
            {
              "name": "CaptchaOptions:IsEnabled",
              "value": "false",
              "slotSetting": true
            },
            {
              "name": "AzureWebJobs.OrderChanged.Disabled",
              "value": "true",
              "slotSetting": true
            }
          ]

  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      appName: $(appName)
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      autoSwapSlots: true
