name: niobiumstore
resourceGroup: rg-niobium-store-${AZURE_ENV_NAME}

hooks:
  preprovision:
    shell: pwsh
    run: ./infra/scripts/SetAppSettings.ps1
  postprovision:
    - shell: pwsh
      run: ./infra/scripts/SetKeyVaultSecrets.ps1
    - shell: pwsh
      run: ./infra/scripts/ClearAppSettings.ps1

infra:
  provider: bicep
  layers:
    - name: niobiumstore-infra
      path: ./infra

services:
  niobiumstore:
    project: ./src/Niobium.Store.Server
    language: csharp
    host: function
    hooks:
      prepackage:
        run: dotnet test --solution ../../Niobium.Store.slnx --configuration Release

pipeline:
  provider: github
