name: '1.0$(Rev:.r)'
trigger:
- master

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'niobium-store'
  resourceGroupName: 'niobium-store'
  appName: 'niobiumstoreFunc'
  assetsPageName: 'assets-store-niobium-co-nz'

  orderCreateEventQueueName: 'ordercreatedevent'
  orderSettledEventQueueName: 'ordersettledevent'
  fulfillOrderCommandQueueName: 'fulfillordercommand'
  updateTrackingCommandQueueName: 'updatetrackingcommand'
  invoiceServiceBusResourceGroup: 'niobium-invoicing' 
  notificationServiceBusResourceGroup: 'niobium-ntfy'
  enableStagingSlot: true
  
  tableDB: 'niobiumstoredb'
  serviceBusNamespace: 'niobiumstoresb'  
  notificationServiceBusNamespace: 'niobiumntfysb'
  invoiceServiceBusNamespace: 'niobiuminvoicingsb'

  tableDBStaging: 'niobiumstoredbstaging'
  serviceBusNamespaceStaging: 'niobiumstoresbstaging'  
  notificationServiceBusNamespaceStaging: 'niobiumntfysbstaging'
  invoiceServiceBusNamespaceStaging: 'niobiuminvoicingsbstaging'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'Niobium/niobium'
      projectToPublish: '**/Niobium.Store.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appName: $(appName)
      enableKeyVault: true
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      allowedOrigins: '*'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        sku: 'Standard_LRS'
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: $(tableDB)
        contributorPrincipalId: $(functionAppPrincipalId)
        allowedOrigins: '*'
        outputVariableName: 'newStorageAccountProperties'
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        sku: 'Standard_LRS'
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: $(tableDBStaging)
        contributorPrincipalId: $(functionAppPrincipalIdStaging)
        allowedOrigins: '*'
        outputVariableName: 'newStorageAccountPropertiesStaging'

  - job: Messaging
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: $(serviceBusNamespace)
        serviceBusQueueNames: [$(orderCreateEventQueueName), $(orderSettledEventQueueName), $(fulfillOrderCommandQueueName), $(updateTrackingCommandQueueName)]
        dataOwnerPrincipalId: $(functionAppPrincipalId)
        outputVariableName: 'newServiceBusProperties'
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: $(serviceBusNamespaceStaging)
        serviceBusQueueNames: [$(orderCreateEventQueueName), $(orderSettledEventQueueName), $(fulfillOrderCommandQueueName), $(updateTrackingCommandQueueName)]
        dataOwnerPrincipalId: $(functionAppPrincipalIdStaging)
        outputVariableName: 'newServiceBusPropertiesStaging'

  - job: NotificationRBAC
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(notificationServiceBusResourceGroup)
        serviceBusNamespaceName: $(notificationServiceBusNamespace)
        dataOwnerPrincipalId: $(functionAppPrincipalId)
        outputVariableName: 'serviceBusPermissionProperties'
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(notificationServiceBusResourceGroup)
        serviceBusNamespaceName: $(notificationServiceBusNamespaceStaging)
        dataOwnerPrincipalId: $(functionAppPrincipalIdStaging)
        outputVariableName: 'serviceBusPermissionPropertiesStaging'

  - job: InvoiceRBAC
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(invoiceServiceBusResourceGroup)
        serviceBusNamespaceName: $(invoiceServiceBusNamespace)
        dataOwnerPrincipalId: $(functionAppPrincipalId)
        outputVariableName: 'serviceBusPermissionProperties'
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(invoiceServiceBusResourceGroup)
        serviceBusNamespaceName: $(invoiceServiceBusNamespaceStaging)
        dataOwnerPrincipalId: $(functionAppPrincipalIdStaging)
        outputVariableName: 'serviceBusPermissionPropertiesStaging'

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
      - Messaging
      - NotificationRBAC
      - InvoiceRBAC
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      serviceBusFQDN: $[dependencies.Messaging.outputs['newServiceBusProperties.fullyQualifiedNamespace']]
      notificationServiceBusFQDN: $[dependencies.NotificationRBAC.outputs['serviceBusPermissionProperties.fullyQualifiedNamespace']]
      invoiceServiceBusFQDN: $[dependencies.InvoiceRBAC.outputs['serviceBusPermissionProperties.fullyQualifiedNamespace']]
      tableFQDNStaging: $[dependencies.Table.outputs['newStorageAccountPropertiesStaging.tableFQDN']]
      serviceBusFQDNStaging: $[dependencies.Messaging.outputs['newServiceBusPropertiesStaging.fullyQualifiedNamespace']]
      notificationServiceBusFQDNStaging: $[dependencies.NotificationRBAC.outputs['serviceBusPermissionPropertiesStaging.fullyQualifiedNamespace']]
      invoiceServiceBusFQDNStaging: $[dependencies.InvoiceRBAC.outputs['serviceBusPermissionPropertiesStaging.fullyQualifiedNamespace']]
    steps:
    - checkout: none
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]production"
      displayName: "Deploy to Production"
      condition: eq('${{ variables.enableStagingSlot }}', false)
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]staging"
      displayName: "Deploy to Staging"
      condition: eq('${{ variables.enableStagingSlot }}', true)
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "StoreOptions:InvoicingTenant",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusTriggerOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "NotificationQueueOptions:FullyQualifiedNamespace",
              "value": "$(notificationServiceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "InvoiceQueueOptions:FullyQualifiedNamespace",
              "value": "$(invoiceServiceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretAPIKey",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/STRIPE-SECRET/)",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretHashKey",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/HASH-SECRET/)",
              "slotSetting": true
            },
            {
                "name": "CaptchaOptions:Secrets:www.niobium.co.nz",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RECAPTCHA-WWW-NIOBIUM-CO-NZ/)",
                "slotSetting": true
            },
            {
                "name": "CaptchaOptions:Secrets:www.zaps.co.nz",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RECAPTCHA-WWW-ZAPS-CO-NZ/)",
                "slotSetting": true
            }
          ]
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        slotName: $(slotName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "StoreOptions:InvoicingTenant",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusTriggerOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "NotificationQueueOptions:FullyQualifiedNamespace",
              "value": "$(notificationServiceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "InvoiceQueueOptions:FullyQualifiedNamespace",
              "value": "$(invoiceServiceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretAPIKey",
              "value": "sk_test_51RSwkoRt21XMpal8PaJpf5l6bGSGtgU1bueDBUL5mJw16bv5jPegj99Yw5yAXRSqaL0n0lFoan6JA6FOUdZWKKbb00a4PHlbrS",
              "slotSetting": true
            },
            {
              "name": "PaymentServiceOptions:SecretHashKey",
              "value": "012345678901234567890123456789AB",
              "slotSetting": true
            },
            {
              "name": "CaptchaOptions:IsDisabled",
              "value": "true",
              "slotSetting": true
            }
          ]

  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      appName: $(appName)
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      autoSwapSlots: false

  - job: Testing
    dependsOn: 
      - Deploy
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      API_URL: 'https://staging.api.store.niobium.co.nz'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(System.DefaultWorkingDirectory)/Niobium.Store.IntegrationTests'
      displayName: 'npm install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'test'
        workingDir: '$(System.DefaultWorkingDirectory)/Niobium.Store.IntegrationTests'
      displayName: 'npm test'

  - job: Swap
    dependsOn: 
      - Testing
    condition: and(succeeded(), eq('${{ variables.enableStagingSlot }}', true))
    steps:
    - task: AzureAppServiceManage@0
      displayName: 'Swap Production'
      inputs:
        azureSubscription: $(serviceConnection)
        ResourceGroupName: $(resourceGroupName)
        Action: 'Swap Slots'
        WebAppName: $(appName)
        SourceSlot: 'staging'
        SwapWithProduction: true

  - template: pipelines/jobs/AssetsDeploy.yml@devops
    parameters:
      cloudflarePagesProjectName: $(assetsPageName)
      cloudflareAccountID: $(cloudflareAccountID)
      cloudflareAPIToken: $(cloudflareAPIToken)
