services:
  niobium.store.host:
    image: ${DOCKER_REGISTRY-}niobiumstore
    build:
      context: .
      dockerfile: src/Niobium.Store.Host/Dockerfile
    env_file:
      - .azure/dev/.env
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"
    depends_on:
      aspire-dashboard:
        condition: service_started
      azurite:
        condition: service_started

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888" # Dashboard Web UI
      - "4317:18889"  # OTLP gRPC port
      - "4318:18890"  # OTLP HTTP port
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    hostname: azurite
    restart: unless-stopped
    ports:
      - "10000:10000" # Blob Service
      - "10001:10001" # Queue Service
      - "10002:10002" # Table Service