name: Publish

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  buildVersion: '${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ github.run_number }}'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'test'
    concurrency:
      group: test-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: azd login
        run: azd auth login --federated-credential-provider github --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Publish
        env:
          AZURE_LOCATION: 'australiaeast'
          AZURE_ENV_NAME: 'test'
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          IS_INTERACTIVE_DEPLOYER: false
          APPSETTING_SERVICE_NAME: 'Niobium.Store.Server.Test'
          APPSETTING_SERVICE_VERSION: '${{ env.buildVersion }}-prerelease'
          APPSETTING_CAPTCHAOPTIONS__ISDISABLED: 'true'
          APPSETTING_STOREOPTIONS__INVOICINGTENANT: '95b52e52-dc79-4ac0-a53f-1acb10238888'
          APPSETTING_INVOICEQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiuminvoicing-sb-test.servicebus.windows.net'
          APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiumnotify-sb-test.servicebus.windows.net'
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETAPIKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETHASHKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
        run: |
          azd package --no-prompt
          azd provision --no-state --no-prompt
          azd deploy --no-prompt
      
      - name: Integration tests
        working-directory: src/Niobium.Store.IntegrationTests
        env:
          API_URL: 'https://${{ secrets.CUSTOM_DOMAIN_NAME }}'
        run: |
          npm install
          npm test

  prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 'prod'
    concurrency:
      group: production-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: azd login
        run: azd auth login --federated-credential-provider github --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Publish
        env:
          AZURE_LOCATION: 'australiaeast'
          AZURE_ENV_NAME: 'prod'
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          IS_INTERACTIVE_DEPLOYER: false
          APPSETTING_SERVICE_NAME: 'Niobium.Store.Server.Prod'
          APPSETTING_SERVICE_VERSION: ${{ env.buildVersion }}
          APPSETTING_CAPTCHAOPTIONS__ISDISABLED: 'false'
          APPSETTING_STOREOPTIONS__INVOICINGTENANT: '95b52e52-dc79-4ac0-a53f-1acb10238888'
          APPSETTING_INVOICEQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiuminvoicing-sb-prod.servicebus.windows.net'
          APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiumnotify-sb-prod.servicebus.windows.net'
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETAPIKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETHASHKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY }}
          APPSETTING_KV_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE }}
          APPSETTING_KV_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ }}
          APPSETTING_KV_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_KV_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
        run: |
          azd package --no-prompt
          azd provision --no-state --no-prompt
          azd deploy --no-prompt
      
      - name: Deploy assets
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy "./assets" --project-name="assets-store-niobium-co-nz" --branch=main
