name: Publish

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'test'
      version_suffix: '-prerelease'
      run_integration_test: true
      deploy_assets: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
      CUSTOM_DOMAIN_CERTIFICATE_NAME: ${{ secrets.CUSTOM_DOMAIN_CERTIFICATE_NAME }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY }}
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}

  prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'prod'
      version_suffix: ''
      run_integration_test: false
      deploy_assets: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
      CUSTOM_DOMAIN_CERTIFICATE_NAME: ${{ secrets.CUSTOM_DOMAIN_CERTIFICATE_NAME }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY }}
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
