name: Publish

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'test'
      custom_domain: 'staging.api.store.niobium.co.nz'
      version_suffix: '-prerelease'
      deploy_assets: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SELF_HOSTNAME: ${{ secrets.SELF_HOSTNAME }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'prod'
      custom_domain: 'api.store.niobium.co.nz'
      version_suffix: ''
      deploy_assets: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SELF_HOSTNAME: ${{ secrets.SELF_HOSTNAME }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
