name: Reusable publish job

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version_suffix:
        required: false
        type: string
        default: ''
      deploy_assets:
        required: false
        type: boolean
        default: false
      run_integration_test:
        required: false
        type: boolean
        default: true
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: false
      CLOUDFLARE_ACCOUNT_ID:
        required: false
      CUSTOM_DOMAIN_NAME:
        required: false
      CUSTOM_DOMAIN_CERTIFICATE_NAME:
        required: false
      APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE:
        required: false
      APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ:
        required: false
      APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ:
        required: false
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY:
        required: true
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY:
        required: true
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5:
        required: false
      APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD:
        required: false
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5:
        required: false
      APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SERVICE_NAME: "Niobium.Store.Host"
      VERSION_MAJOR: 1
      VERSION_MINOR: 0
      VERSION_SUFFIX: ${{ inputs.version_suffix }}
      SERVICE_BUS_QUEUES: "ordercreatedevent,updatetrackingcommand,orderdeliveredevent,ordersettledevent,ordershippedevent"
      CLOUDFLARE_ASSETS_PROJECT: "assets-store-niobium-co-nz"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: azd login
        run: azd auth login --federated-credential-provider github --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Publish
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ inputs.environment }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          CUSTOM_DOMAIN_CERTIFICATE_NAME: ${{ secrets.CUSTOM_DOMAIN_CERTIFICATE_NAME }}
          SERVICE_BUS_QUEUE_NAMES: ${{ env.SERVICE_BUS_QUEUES }}
          APPSETTING_SERVICE_NAME: ${{ env.SERVICE_NAME }}
          APPSETTING_SERVICE_VERSION: '${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{ github.run_number }}${{ env.VERSION_SUFFIX }}'
          APPSETTING_CAPTCHAOPTIONS__ISDISABLED: ${{ vars.APPSETTING_CAPTCHAOPTIONS__ISDISABLED }}
          APPSETTING_STOREOPTIONS__INVOICINGTENANT: ${{ vars.APPSETTING_STOREOPTIONS__INVOICINGTENANT }}
          APPSETTING_INVOICEQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: ${{ vars.APPSETTING_INVOICEQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE }}
          APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: ${{ vars.APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE }}
          APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__TAPSS_CARE }}
          APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__NIOBIUM_CO_NZ }}
          APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__ZAPS_CO_NZ }}
          APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETAPIKEY }}
          APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETHASHKEY }}
          APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__HASHES__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
          APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__2AAD53C9_9849_43A9_BCD7_50425B3249D5 }}
          APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD: ${{ secrets.APPSETTING_PAYMENTSERVICEOPTIONS__SECRETS__DE8B3E50_ABF6_4CDD_9269_F2472A1020AD }}
        run: |
          azd package --no-prompt
          azd provision --no-state --no-prompt
          azd deploy --no-prompt

      - name: Integration tests
        if: ${{ inputs.run_integration_test }}
        working-directory: src/Niobium.Store.IntegrationTests
        env:
          API_URL: 'https://${{ secrets.CUSTOM_DOMAIN_NAME }}'
        run: |
          npm install
          npm test

      - name: Deploy assets
        if: ${{ inputs.deploy_assets }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy "./assets" --project-name="${{ env.CLOUDFLARE_ASSETS_PROJECT }}" --branch=main
